-----------------------------------
-- Coalition Assignment spec: all 95 assignments, one row each.
--
-- GENERATED by tools/coalition/gen_assignment_data.py. Read that file for
-- where every column comes from; the short version is that the zone slot
-- numbering, the turn-in items and the Patrol and Research quarry are the
-- client's own (Task Delegator events 2007 to 2012 in zones 256 and 257),
-- and the rank gate and reward figures are bg-wiki's.
--
-- zoneSlot is the row order of the client's assignment list, message 7373.
-- altSlot is the second zone bg-wiki allows for the assignments that name
-- one ("either Ceizak Battlegrounds or Yahse Hunting Grounds").
--
-- reward is the EXP and the Bayld paid for spending ONE imprimatur. Two
-- pays 1.8x and three pays 2.4x, which is how bg-wiki's three columns
-- relate across all 95 rows, so only the base is stored.
-----------------------------------
xi = xi or {}
xi.coalitionAssignments = xi.coalitionAssignments or {}

-- Client zone slot to zone id. Slots 0 and 1 are the two city zones, which
-- no assignment uses; 17 and 18 are the client's unused placeholders.
xi.coalitionAssignments.zoneForSlot =
{
    [ 0] = xi.zone.WESTERN_ADOULIN,
    [ 1] = xi.zone.EASTERN_ADOULIN,
    [ 2] = xi.zone.RALA_WATERWAYS,
    [ 3] = xi.zone.CEIZAK_BATTLEGROUNDS,
    [ 4] = xi.zone.YAHSE_HUNTING_GROUNDS,
    [ 5] = xi.zone.FORET_DE_HENNETIEL,
    [ 6] = xi.zone.MORIMAR_BASALT_FIELDS,
    [ 7] = xi.zone.YORCIA_WEALD,
    [ 8] = xi.zone.MARJAMI_RAVINE,
    [ 9] = xi.zone.KAMIHR_DRIFTS,
    [10] = xi.zone.SIH_GATES,
    [11] = xi.zone.MOH_GATES,
    [12] = xi.zone.CIRDAS_CAVERNS,
    [13] = xi.zone.DHO_GATES,
    [14] = xi.zone.WOH_GATES,
    [15] = xi.zone.OUTER_RAKAZNAR,
    [16] = xi.zone.RAKAZNAR_INNER_COURT,
}

-- Assignment kinds, and the (coalition, type index) address the client
-- files each one under.
---@enum xi.coalitionAssignments.kind
xi.coalitionAssignments.kind =
{
    PROCURE   = 1,
    CLEAR     = 2,
    PRESERVE  = 3,
    PATROL    = 4,
    PROVIDE   = 5,
    DELIVER   = 6,
    SUPPORT   = 7,
    SURVEY    = 8,
    ANALYZE   = 9,
    GATHER    = 10,
    RECOVER   = 11,
    RESEARCH  = 12,
    BOOST     = 13,
}

xi.coalitionAssignments.kindInfo =
{
    [xi.coalitionAssignments.kind.PROCURE] = { coalition = xi.coalition.PIONEERS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.CLEAR] = { coalition = xi.coalition.PIONEERS, typeIndex = 2 },
    [xi.coalitionAssignments.kind.PRESERVE] = { coalition = xi.coalition.PEACEKEEPERS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.PATROL] = { coalition = xi.coalition.PEACEKEEPERS, typeIndex = 2 },
    [xi.coalitionAssignments.kind.PROVIDE] = { coalition = xi.coalition.COURIERS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.DELIVER] = { coalition = xi.coalition.COURIERS, typeIndex = 2 },
    [xi.coalitionAssignments.kind.SUPPORT] = { coalition = xi.coalition.COURIERS, typeIndex = 3 },
    [xi.coalitionAssignments.kind.SURVEY] = { coalition = xi.coalition.SCOUTS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.ANALYZE] = { coalition = xi.coalition.SCOUTS, typeIndex = 2 },
    [xi.coalitionAssignments.kind.GATHER] = { coalition = xi.coalition.INVENTORS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.RECOVER] = { coalition = xi.coalition.MUMMERS, typeIndex = 1 },
    [xi.coalitionAssignments.kind.RESEARCH] = { coalition = xi.coalition.MUMMERS, typeIndex = 2 },
    [xi.coalitionAssignments.kind.BOOST] = { coalition = xi.coalition.MUMMERS, typeIndex = 3 },
}

-- Personal standing tiers, read out of client message 7506.
---@enum xi.coalitionAssignments.rank
xi.coalitionAssignments.rank =
{
    PETITIONER   = 1,
    PROBATIONER  = 2,
    DISCIPLE     = 3,
    CONTRIBUTOR  = 4,
    PARTNER      = 5,
    ADVISOR      = 6,
    MAGNATE      = 7,
    LEGEND       = 8,
}

xi.coalitionAssignments.rankNames =
{
    [1] = 'Petitioner',
    [2] = 'Probationer',
    [3] = 'Disciple',
    [4] = 'Contributor',
    [5] = 'Partner',
    [6] = 'Advisor',
    [7] = 'Magnate',
    [8] = 'Legend',
}

-- Which reive a Clear or Preserve assignment credits. Message 7378 offers
-- all three, and only the first two gate an assignment.
---@enum xi.coalitionAssignments.reive
xi.coalitionAssignments.reive =
{
    COLONIZATION = 1,
    LAIR         = 2,
}

-- One row per assignment, keyed by the declared quest id. The aliases keep
-- a row on one line; they are only used while this table is built.
local kind  = xi.coalitionAssignments.kind
local rank  = xi.coalitionAssignments.rank
local reive = xi.coalitionAssignments.reive

xi.coalitionAssignments.spec =
{
    -- Pioneers: Procuring Resources. 7375 'procure N materials by <method>'.
    [ 0] = { kind = kind.PROCURE, slot = 3, alt = 4, rank = rank.PETITIONER, reward = 1500, count = 5, helm = xi.helmType.LOGGING },
    [ 1] = { kind = kind.PROCURE, slot = 5, rank = rank.DISCIPLE, reward = 2000, count = 5, helm = xi.helmType.HARVESTING },
    [ 2] = { kind = kind.PROCURE, slot = 6, rank = rank.DISCIPLE, reward = 2000, count = 5, helm = xi.helmType.MINING },
    [ 3] = { kind = kind.PROCURE, slot = 7, rank = rank.ADVISOR, reward = 3750, count = 5, helm = xi.helmType.LOGGING },
    [ 4] = { kind = kind.PROCURE, slot = 8, rank = rank.PARTNER, reward = 3000, count = 5, helm = xi.helmType.MINING },
    [ 5] = { kind = kind.PROCURE, slot = 9, rank = rank.MAGNATE, reward = 4500, count = 5, helm = xi.helmType.MINING },
    [ 6] = { kind = kind.PROCURE, slot = 12, rank = rank.CONTRIBUTOR, reward = 2500, count = 5, helm = xi.helmType.MINING },
    [ 7] = { kind = kind.PROCURE, slot = 15, rank = rank.LEGEND, reward = 6000, count = 5, helm = xi.helmType.MINING },

    -- Pioneers: Clearing the Way. Colonization Reive, 7378 param 1 = 0.
    [ 8] = { kind = kind.CLEAR, slot = 3, alt = 4, rank = rank.PETITIONER, reward = 1750, reive = reive.COLONIZATION },
    [ 9] = { kind = kind.CLEAR, slot = 5, rank = rank.PROBATIONER, reward = 2500, reive = reive.COLONIZATION },
    [10] = { kind = kind.CLEAR, slot = 6, rank = rank.PROBATIONER, reward = 2500, reive = reive.COLONIZATION },
    [11] = { kind = kind.CLEAR, slot = 7, rank = rank.ADVISOR, reward = 5000, reive = reive.COLONIZATION },
    [12] = { kind = kind.CLEAR, slot = 8, rank = rank.PARTNER, reward = 4250, reive = reive.COLONIZATION },
    [13] = { kind = kind.CLEAR, slot = 9, rank = rank.MAGNATE, reward = 6000, reive = reive.COLONIZATION },
    [14] = { kind = kind.CLEAR, slot = 12, rank = rank.CONTRIBUTOR, reward = 4000, reive = reive.COLONIZATION },
    [15] = { kind = kind.CLEAR, slot = 15, alt = 16, rank = rank.LEGEND, reward = 7000, reive = reive.COLONIZATION },

    -- Couriers: Base Provisions. Retired on retail, never offered.
    [16] = { kind = kind.PROVIDE, slot = 5, rank = rank.PROBATIONER, reward = 1250, retired = true },
    [17] = { kind = kind.PROVIDE, slot = 6, rank = rank.PROBATIONER, reward = 1250, retired = true },
    [18] = { kind = kind.PROVIDE, slot = 7, rank = rank.PARTNER, reward = 2500, retired = true },
    [19] = { kind = kind.PROVIDE, slot = 8, rank = rank.PARTNER, reward = 2500, retired = true },
    [20] = { kind = kind.PROVIDE, slot = 9, rank = rank.MAGNATE, reward = 3500, retired = true },

    -- Couriers: Supply Delivery. 7392 station to desk, 7395 waypoints break it.
    [21] = { kind = kind.DELIVER, slot = 5, rank = rank.CONTRIBUTOR, reward = 2000 },
    [22] = { kind = kind.DELIVER, slot = 6, rank = rank.CONTRIBUTOR, reward = 2000 },
    [23] = { kind = kind.DELIVER, slot = 7, rank = rank.ADVISOR, reward = 2500 },
    [24] = { kind = kind.DELIVER, slot = 8, rank = rank.ADVISOR, reward = 2500 },
    [25] = { kind = kind.DELIVER, slot = 9, rank = rank.LEGEND, reward = 4500 },

    -- Couriers: Frontline Support. 7393 supplies to a frontier bivouac.
    [26] = { kind = kind.SUPPORT, slot = 3, alt = 4, rank = rank.PETITIONER, reward = 1000 },
    [27] = { kind = kind.SUPPORT, slot = 5, rank = rank.DISCIPLE, reward = 1500 },
    [28] = { kind = kind.SUPPORT, slot = 6, rank = rank.DISCIPLE, reward = 1500 },
    [29] = { kind = kind.SUPPORT, slot = 7, rank = rank.ADVISOR, reward = 3000 },
    [30] = { kind = kind.SUPPORT, slot = 8, rank = rank.ADVISOR, reward = 3000 },
    [31] = { kind = kind.SUPPORT, slot = 9, rank = rank.MAGNATE, reward = 3500 },

    -- Inventors: Gather Materials. Items are the client's 5103..5117 run.
    [32] = { kind = kind.GATHER, slot = 2, rank = rank.PETITIONER, reward = 1000, item = 1700, count = 3 },
    [33] = { kind = kind.GATHER, slot = 3, rank = rank.PETITIONER, reward = 1000, item = 3941, count = 5 },
    [34] = { kind = kind.GATHER, slot = 4, rank = rank.PETITIONER, reward = 1000, item = 3930, count = 5 },
    [35] = { kind = kind.GATHER, slot = 5, rank = rank.DISCIPLE, reward = 1750, item = 3933, count = 3 },
    [36] = { kind = kind.GATHER, slot = 6, rank = rank.DISCIPLE, reward = 1750, item = 2524, count = 3 },
    [37] = { kind = kind.GATHER, slot = 7, rank = rank.ADVISOR, reward = 3250, item = 4032, count = 3 },
    [38] = { kind = kind.GATHER, slot = 8, rank = rank.PARTNER, reward = 2750, item = 4016, count = 3 },
    [39] = { kind = kind.GATHER, slot = 9, rank = rank.MAGNATE, reward = 4000, item = 8709, count = 3 },
    [40] = { kind = kind.GATHER, slot = 10, rank = rank.PROBATIONER, reward = 1250, item = 3936, count = 3 },
    [41] = { kind = kind.GATHER, slot = 11, rank = rank.PROBATIONER, reward = 1250, item = 3934, count = 3 },
    [42] = { kind = kind.GATHER, slot = 12, rank = rank.CONTRIBUTOR, reward = 2250, item = 3935, count = 3 },
    [43] = { kind = kind.GATHER, slot = 13, rank = rank.PARTNER, reward = 2750, item = 2509, count = 3 },
    [44] = { kind = kind.GATHER, slot = 14, rank = rank.MAGNATE, reward = 4000, item = 17306, count = 3 },
    [45] = { kind = kind.GATHER, slot = 15, rank = rank.LEGEND, reward = 4750, item = 8746, count = 1 },
    [46] = { kind = kind.GATHER, slot = 16, rank = rank.LEGEND, reward = 4750, item = 529, count = 3 },

    -- Scouts: Land Surveys. 7399 survey an ergon locus.
    [48] = { kind = kind.SURVEY, slot = 3, alt = 4, rank = rank.PETITIONER, reward = 1000 },
    [49] = { kind = kind.SURVEY, slot = 5, rank = rank.DISCIPLE, reward = 1500 },
    [50] = { kind = kind.SURVEY, slot = 6, rank = rank.DISCIPLE, reward = 1500 },
    [51] = { kind = kind.SURVEY, slot = 7, rank = rank.ADVISOR, reward = 3000 },
    [52] = { kind = kind.SURVEY, slot = 8, rank = rank.ADVISOR, reward = 3000 },
    [53] = { kind = kind.SURVEY, slot = 9, rank = rank.MAGNATE, reward = 3500 },
    [54] = { kind = kind.SURVEY, slot = 10, alt = 11, rank = rank.PROBATIONER, reward = 1250 },
    [55] = { kind = kind.SURVEY, slot = 12, rank = rank.CONTRIBUTOR, reward = 2000 },
    [56] = { kind = kind.SURVEY, slot = 13, alt = 14, rank = rank.PARTNER, reward = 2500 },

    -- Scouts: Component Analyses. Items are the client's 4206..4216 run.
    [57] = { kind = kind.ANALYZE, slot = 5, rank = rank.CONTRIBUTOR, reward = 2250, item = 5984, count = 1 },
    [58] = { kind = kind.ANALYZE, slot = 6, rank = rank.CONTRIBUTOR, reward = 2250, item = 3921, count = 1 },
    [59] = { kind = kind.ANALYZE, slot = 7, rank = rank.MAGNATE, reward = 4000, item = 4018, count = 1 },
    [60] = { kind = kind.ANALYZE, slot = 8, rank = rank.MAGNATE, reward = 4000, item = 1469, count = 1 },
    [61] = { kind = kind.ANALYZE, slot = 9, rank = rank.LEGEND, reward = 4750, item = 4057, count = 1 },
    [62] = { kind = kind.ANALYZE, slot = 12, rank = rank.PARTNER, reward = 2750, item = 3924, count = 1 },
    [63] = { kind = kind.ANALYZE, slot = 15, rank = rank.LEGEND, reward = 5500, item = 3920, count = 1 },

    -- Peacekeepers: Preserve the Peace. Lair Reive, 7378 param 1 = 1.
    [64] = { kind = kind.PRESERVE, slot = 3, rank = rank.PETITIONER, reward = 1750, reive = reive.LAIR },
    [65] = { kind = kind.PRESERVE, slot = 4, rank = rank.PETITIONER, reward = 1750, reive = reive.LAIR },
    [66] = { kind = kind.PRESERVE, slot = 5, rank = rank.DISCIPLE, reward = 3250, reive = reive.LAIR },
    [67] = { kind = kind.PRESERVE, slot = 6, rank = rank.DISCIPLE, reward = 3250, reive = reive.LAIR },
    [68] = { kind = kind.PRESERVE, slot = 7, rank = rank.ADVISOR, reward = 5000, reive = reive.LAIR },
    [69] = { kind = kind.PRESERVE, slot = 8, rank = rank.ADVISOR, reward = 5000, reive = reive.LAIR },
    [70] = { kind = kind.PRESERVE, slot = 9, rank = rank.MAGNATE, reward = 6000, reive = reive.LAIR },
    [71] = { kind = kind.PRESERVE, slot = 12, rank = rank.CONTRIBUTOR, reward = 4000, reive = reive.LAIR },
    [72] = { kind = kind.PRESERVE, slot = 15, alt = 16, rank = rank.LEGEND, reward = 7000, reive = reive.LAIR },

    -- Peacekeepers: Patrol. Quarry per zone slot is message 7385 param 1.
    [73] = { kind = kind.PATROL, slot = 2, rank = rank.PROBATIONER, reward = 2500, family = 111, count = 5 },
    [74] = { kind = kind.PATROL, slot = 10, rank = rank.PROBATIONER, reward = 2500, family = 338, count = 5 },
    [75] = { kind = kind.PATROL, slot = 11, rank = rank.PROBATIONER, reward = 2500, family = 210, count = 5 },
    [76] = { kind = kind.PATROL, slot = 12, rank = rank.PARTNER, reward = 4250, family = 347, count = 3 },
    [77] = { kind = kind.PATROL, slot = 13, rank = rank.PARTNER, reward = 4250, family = 98, count = 3 },
    [78] = { kind = kind.PATROL, slot = 14, rank = rank.MAGNATE, reward = 6000, family = 345, count = 3 },
    [79] = { kind = kind.PATROL, slot = 15, rank = rank.LEGEND, reward = 8000, family = 350, count = 3 },

    -- Mummers: Recovering Lost Articles. 7412 find a lost article.
    [80] = { kind = kind.RECOVER, slot = 3, alt = 4, rank = rank.PETITIONER, reward = 1500 },
    [81] = { kind = kind.RECOVER, slot = 5, alt = 10, rank = rank.DISCIPLE, reward = 2000 },
    [82] = { kind = kind.RECOVER, slot = 6, alt = 11, rank = rank.DISCIPLE, reward = 2000 },
    [83] = { kind = kind.RECOVER, slot = 7, alt = 12, rank = rank.ADVISOR, reward = 3750 },
    [84] = { kind = kind.RECOVER, slot = 8, alt = 13, rank = rank.PARTNER, reward = 3000 },
    [85] = { kind = kind.RECOVER, slot = 9, alt = 14, rank = rank.LEGEND, reward = 5250 },

    -- Mummers: Behavioral Research. Quarry per zone slot is message 7414.
    [86] = { kind = kind.RESEARCH, slot = 2, rank = rank.PETITIONER, reward = 1750, family = 231 },
    [87] = { kind = kind.RESEARCH, slot = 3, alt = 4, rank = rank.PROBATIONER, reward = 2500, family = 339 },
    [88] = { kind = kind.RESEARCH, slot = 5, alt = 10, rank = rank.CONTRIBUTOR, reward = 4000, family = 344 },
    [89] = { kind = kind.RESEARCH, slot = 6, alt = 11, rank = rank.CONTRIBUTOR, reward = 4000, family = 348 },
    [90] = { kind = kind.RESEARCH, slot = 7, rank = rank.MAGNATE, reward = 6000, family = 464 },
    [91] = { kind = kind.RESEARCH, slot = 8, rank = rank.ADVISOR, reward = 5000, family = 454 },
    [92] = { kind = kind.RESEARCH, slot = 9, rank = rank.LEGEND, reward = 8000, family = 458 },

    -- Mummers: Morale Boosting. 7417 cheer the frontier station staff.
    [93] = { kind = kind.BOOST, slot = 5, alt = 6, rank = rank.PROBATIONER, reward = 1750 },
    [94] = { kind = kind.BOOST, slot = 8, alt = 7, rank = rank.PARTNER, reward = 3500 },
    [95] = { kind = kind.BOOST, slot = 9, rank = rank.MAGNATE, reward = 5000 },
}
