# Set DEVTOOLS_IMAGE repo var to use a different devtools image. Default: ghcr.io/landsandboat/devtools:ubuntu

name: Tests

on:
  workflow_run:
    workflows: [Builds]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Docker_Test:
    name: ${{ matrix.os && 'Test' || '' }} # GitHub Actions hack to hide matrix args
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    uses: ./.github/workflows/docker_test.yml
    with:
      os: ${{ matrix.os }}
